### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Joltrix** [StarcounterApps/Notes#3]
- [ ] Notes app should create a Note, which in turn will create an event. A Note should not be an event by itself.
- [ ] Add additional functionality.
- [ ] Make Notes app usable by itself
- [ ] Idea: Perhaps make Notes behave similar to Google Keep. And let it be a way of storing "memos".
